# This file was generated by GoReleaser. DO NOT EDIT.
class BlackboxOs < Formula
  desc "A pluggable platform for multi-chain deployments."
  homepage "https://crypdex.io/"
  url "https://github.com/crypdex/blackbox/releases/download/0.2.1/blackbox-os_0.2.1_darwin_amd64.tar.gz"
  version "0.2.1"
  sha256 "d8755700be7fa09de5c2e692dd09db3e8efcbb99a5ab3d82719fd6b93813316f"

  def install
    bin.install "blackbox"
  end
end
