# This file was generated by GoReleaser. DO NOT EDIT.
class Blackboxd < Formula
  desc "A pluggable platform for multi-chain deployments."
  homepage "https://crypdex.io/"
  url "https://github.com/crypdex/blackbox/releases/download/0.1.51/blackboxd_0.1.51_darwin_amd64.tar.gz"
  version "0.1.51"
  sha256 "1529161c1958d67abd31c69f71706278e67c986460d5b6195ed626f7288ca50e"

  def install
    bin.install "blackboxd"
  end
end
