# This file was generated by GoReleaser. DO NOT EDIT.
class Blackboxd < Formula
  desc "A pluggable platform for multi-chain deployments."
  homepage "https://crypdex.io/"
  version "0.2.0-rc5"

  if OS.mac?
    url "https://github.com/crypdex/blackbox/releases/download/0.2.0-rc5/blackboxd_0.2.0-rc5_darwin_amd64.tar.gz"
    sha256 "7816674b951600c0ecebb01eacd76acf74a53b10acfe793569466937785dd4e5"
  elsif OS.linux?
    url "https://github.com/crypdex/blackbox/releases/download/0.2.0-rc5/blackboxd_0.2.0-rc5_linux_amd64.tar.gz"
    sha256 "76ec95defbc388fa9be1f56748b07bece51329812c73f86bad2099c1194cf892"
  end

  def install
    bin.install "blackboxd"
  end
end
